spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baseline-on-migrate: true
  cache:
    type: redis
  redis:
    host: ${REDIS_URL}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  mail:
    host: ${MAIL_URL}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: secret